---
title: "index"
output: html_document
date: '2022-05-17'
---

```{r setup, include = FALSE}
source("summary.R")
source("table.R")

```


### Introduction Paragraph
Write an introductory paragraph explaining the domain/data set (feel free to borrow from the project proposal)

The datasets that we used was a COVID-19 dataset and a COVID Vaccination dataset. In the COVID-19 dataset, it contains data on the statistics of COVID in countries around the world. This data within this dataset has been collected since the start of the pandemic and has been generated by an organization known as Our World in Data in collaboration with the University of Oxford. The COVID Vaccination dataset has also been generated by the organization, Our World in Data, and contains the statistics of the COVID vaccination in countries around the world over time. 


### Summary Paragraph
Write a summary paragraph that includes information calculated by your summary information function

From our summary of the dataset, we can see that there are `r summary_data_info$num_observations` observations and `r summary_data_info$num_features` features. In the dataset, there are a total of `r format(summary_data_info$world_total_cases$total_cases, scientific = FALSE)` cases and `r format(summary_data_info$world_total_deaths$total_deaths, scientific = FALSE)` deaths as `r summary_data_info$world_total_cases$date`
the

The ___ is from ___ to ___


### Table
Render your table and describe pertinent observations found in it

Table is average cases and deaths per date

### Charts
Describe the purpose of each chart (e.g., "this chart was intended to show the relationship between..."), render each chart, and describe pertinent observations found in each chart




