# ui.R

# Load libraries
library("shiny")
library("dplyr")
library("ggplot2")
library("plotly")
library("shinythemes")
library("htmltools")
library("maps")

# Load data frame
covid_data <- read.csv("owid-covid-data.csv")

# Get names for chart pages to use
unique_names <- covid_data %>%
  filter(!is.na(total_vaccinations)) %>%
  group_by(iso_code) %>%
  filter(date == max(date))

continents <- unique_names %>%
  filter(location == "Africa" | location == "Asia" |
         location == "Europe" | location == "North America" |
         location == "Oceania" | location == "South America")

countries <- unique_names %>%
  filter(continent != "")

world <- unique_names %>%
  filter(location == "World")

# Introduction page
introduction <- tabPanel(
  "About",
  titlePanel("Covid-19 Data Analysis"),
  
  sidebarLayout(
    sidebarPanel(
      h2("Data Source"),
      p("The datasets that we used is a COVID-19 dataset. It contains data on the 
        statistics of COVID in countries around the world. The data within this 
        dataset has been collected since the start of the pandemic and has been 
        generated by an organization known as Our World in Data in collaboration 
        with the University of Oxford."),
      tags$img(src = "https://nccid.ca/wp-content/uploads/sites/2/2021/02/COVID-Varients_Twitter.png", width = "100%"),
      p(" "),
      actionButton(inputId = "data_source",
                   label = "Learn More",
                   class = "btn-primary",
                   onclick = "window.open('https://github.com/owid/covid-19-data/tree/master/public/data')")
    ),
    
    mainPanel(
      tags$img(src = "https://phil.cdc.gov//PHIL_Images/23311/23311_lores.jpg", width = "100%"),
      h2("Questions We Hope to Answer: "),
      h3("Which specific countries are most impacted by the pandemic?"),
      p("With this question, we managed to use a world map to clearly display 
        which specific countries have the highest cases and administered vaccinations 
        by analyzing `total_cases` and `total_vaccinations` data based on color coding."),
      h3("What is the correlation between death rate and vaccination rate?"),
      p("With this question, we want to test the relationship strength between 
        the two variables. We will use the `total_deaths` and `total_vaccinations` and 
        dividing them by the population of the location to get the rates and 
        generate a scatterplot which shows the trends generated by two data."),
      h3("Which time period recorded the most new deaths throughout the pandemic?"),
      p("To answer this question, we create a bar chart of `total_deaths` over the 
        months of the pandemic. The color coding demonstrates the severity of the 
        new deaths on each bar, which helps us clearly determine which months were 
        in the peak of Covid-19.")
    )
  )
)

# Chart 1 page - map
chart_1_page <- tabPanel(
  "Total Cases & Vaccinations Map",
  titlePanel("Total Cases & Vaccinations Map"),
  
  sidebarLayout(
    sidebarPanel(
      radioButtons(
        inputId = "radio_data",
        label = h4("Display Data By"),
        choiceNames = c("Total Cases", "Total Vaccinations"),
        choiceValues = c("cases", "vaccinations"),
        selected = "cases"
      )
    ),
    
    mainPanel(
      h3("Total Cases & Vaccinations Map"),
      p("This chart attempts to display an interactive map to show 
        the total COVID cases and vaccinations of all countries/locations."),
      plotlyOutput("map"),
      h3("Which specific countries are most impacted by the pandemic?"),
      p("It shows that the United States, Brazil, and India have been 
        impacted the most with the highest total cases. The map also shows that 
        the United States, Brazil, India, Indonesia, and China have the highest 
        vaccinations in the world. The countries with the highest total cases 
        also have the highest vaccinations.")
    )
  )
)

# Chart 2 page - scatter plot
chart_2_page <- tabPanel(
  "Death rate vs. Vaccination rate Plot",
  titlePanel("Death rate vs. Vaccination rate Plot"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "scatter_choice",
                  label = h4("Select Continent"),
                  choices = list(world$location,
                    "Continent" = continents$location),
                  selected = "World")
    ),
    
    mainPanel(
      h3("Death rate vs. Vaccination rate"),
      p("This chart attempts to display an interactive scatter plot to 
        show the relationship between vaccination rate and death rate
        of all countries/locations grouped by continents."),
      plotlyOutput("plot"),
      h3("What is the correlation between death rate and vaccination rate?"),
      p("The chart shown shows that a lot of African countries 
        have low vaccination rate and low deaths rate. The data of European
         countries shows a trend that as vaccination rate increases, the death
         rate decreases.")
    )
  )
)

# Chart 3 page - bar chart
chart_3_page <- tabPanel(
  "Total Deaths over time Bar Chart",
  titlePanel("Total Deaths over time Chart"),
  
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "bar_choice",
                  label = h4("Select Location"),
                  choices = list(world$location,
                    "Continents" = continents$location,
                    "Country" = countries$location),
                  selected = "World")
    ),
    
    mainPanel(
      h3("Total Deaths over time"),
      p("This chart attempts to display an interactive bar chart to show 
        the total deaths and death rate over time for each location."),
      plotlyOutput("bar_graph"),
      h3("Which time period recorded the most new deaths throughout the pandemic?"),
      p("This chart demonstrates the amount of deaths monthly over time. In
         each country/location, they all have their own unique trend of total deaths over time. 
        In some locations, there is a massive spike and in other there is a slow steady growth.")
    )
  )
)

# Conclusion page
conclusion <- tabPanel(
  "Conclusion",
  titlePanel("Conclusion"),
  h2("Major Takeaways:"),
  h3("Takeaway 1"),
  p("COVID-19 has had an immense impact on the entire world for the past two years 
     and a half. Thankfully, the development of the vaccine has helped mitigate some 
     of the damage and that can be seen in our findings."),
  p("As demonstrated by our map, countries that have been affected the most by the 
    pandemic with a significant amount of cases also have a significant amount of 
    vaccinated individuals."),
  p("The United States, India, Brazil, and Myanmar have had the highest number 
    of COVID-19 cases, and we observed that the United States, China, India, 
    and Brazil have the highest vaccination rates."),
  h3("Takeaway 2"),
  p("Additionally, our observations show that the relationship between death rate 
     and vaccination rate is correlated."),
  p("As more vaccines continue to be administered, the death rate due to 
    COVID-19 decreases. "),
  p("This further emphasises the effect the development of vaccines has had on 
     the world since the first reported cases of the virus."),
  h3("Takeaway 3"),
  p("Finally, cases of new deaths appear to be reducing overtime although some 
     peaks in new deaths can be seen here and there."),
  p("The ebbs and lows can most likely be attributed to variants of COVID that have 
    arised through time."),
  p("Though for the most part in most countries across the word, cases of new 
     deaths can be seen diminishing")
)


ui <- navbarPage(
  "Covid Cases and Vaccinations",
  header = "Team members: Kaia Truong, Aliya Ali, Randy Ros, Vince Qian",
  theme = shinytheme("flatly"),
  introduction,
  chart_1_page,
  chart_2_page,
  chart_3_page,
  conclusion
)
