library("shiny")
library("dplyr")
library("ggplot2")
library("plotly")
library("shinythemes")
library("htmltools")
library("maps")
# Load data frame
covid_data <- read.csv("owid-covid-data.csv")

# Get continent names
continents <- data.frame(unique(covid_data$continent[covid_data$continent != ""]))

# Get country names
countries <- data.frame(unique(covid_data$iso_code[covid_data$continent != ""]))

# Introduction page
introduction <- tabPanel(
  "Summary",
  titlePanel("Covid-19 Data Analysis"),
  br(),
  p("Team members: Kaia Truong, Aliya Ali, Randy Ros, Vince Qian"),
  br(),
  h3("Three main questions we try to answer by this Covid dataset analysis are: "),
  br(),
  h5("First, the number of total case and vaccinations recorded so far around the world so see which specific countries are most impacted by the pandemic."),
  p("With this question, we use our world map to clearly display which specific countries have the highest cases and administered vaccinations by analyzing `total_cases` and `total_vaccinations` data based on color coding."),
  br(),
  h5("Second, the correlation between total deaths and total vaccinations to test the relationship strength between the two variables."),
  p("With this question, we use the `new_deaths` and `new_vaccinations` to generate a scatterplot which shows the trends generated by two data."),
  br(),
  h5("And lastly, which time period record the most new deaths throughout the pandemic with and also the number of total number of deaths over time."),
  p("To answer this question, we create a bar chart of `total_deaths` over the months of the pandemic. The color coding demonstrates the severity of the new deaths on each bar, which helps us clearly determine which months were in the peak of Covid-19."),
  br(),
  HTML('<center><img src="https://phil.cdc.gov//PHIL_Images/23311/23311_lores.jpg"></center>'),
)

# Chart 1 page
chart_1_page <- tabPanel(
  "Total Cases & Vaccinations Map",
  titlePanel("Total Cases & Vaccinations Map"),
  
  sidebarLayout(
    sidebarPanel(
      radioButtons(
        inputId = "radio_data",
        label = h4("Display Data By"),
        choiceNames = c("Total Cases", "Total Vaccinations"),
        choiceValues = c("cases", "vaccinations"),
        selected = "cases"
      )
    ),
    
    # Display bar graph in main panel
    mainPanel(
      h3("Total Cases & Vaccinations Map"),
      h4("Question: Which specific countries have the highest cases and administered the most vaccinations?"),
      plotlyOutput("map"),
      br(),
      h5("Description"),
      p("This map displays the number of total cases and total vaccinations each
         continent has and it shows that the United States, Brazil, and India have been 
        impacted the most with the highest total cases. The map also shows that 
        the United States, Brazil, India, Indonesia, and China have the highest 
        vaccinations in the world. The countries with the highest total cases also have the highest vaccinations.")
    )
  )
)

# Chart 2 page
chart_2_page <- tabPanel(
  "Deaths vs. Vaccinations Plot",
  titlePanel("Deaths vs. Vaccinations Plot"),
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "choose_country_plot",
                  label = h4("Select Continent"),
                  choices = list(
                    "Continent" = continents$unique.covid_data.continent.covid_data.continent........),
                  selected = "Asia")
    ),
    mainPanel(
      h3("Deaths vs. Vaccinations"),
      h4("Question: What is the correlation between total deaths and total vaccinations?"),
      plotlyOutput("plot"),
      br(),
      h5("Description"),
      p("The chart shown shows that a lot of African countries 
        are low vaccination and low new deaths per million. European
         countries have a high new deaths per million and low vaccination. There are a lot of
         Asian countries that have high new vaccination and low deaths per million."),
      p("This also correlates to the total vaccinations map as you can see the same pattern 
        happen in these particular areas.")
    )
  )
)
chart_3_page <- tabPanel(
  "Total Deaths over time Bar Chart",
  titlePanel("Total Deaths over time Chart"),
  sidebarLayout(
    sidebarPanel(
      selectInput(inputId = "choose_country_bar",
                  label = h4("Select Location"),
                  choices = list(
                    "Country" = countries$unique.covid_data.iso_code.covid_data.continent........),
                  selected = "USA")
    ),
    mainPanel(
      h3("Total Deaths over time"),
      h4("Question: Which time period recorded the most new deaths throughout the pandemic?"),
      plotlyOutput("bar_graph"),
      br(),
      h5("Description"),
      p("This chart demonstrates the amount of deaths monthly over time. In
         each country/location, they all have their own unique trend of total deaths over time. 
        In some locations, there is a massive spike and in other there is a slow steady growth.")
    )
  )
)

# Conclusion page
conclusion <- tabPanel(
  "Conclusion",
  titlePanel("Conclusion"),
  h3("Major Takeaways:"),
  br(),
  h5("COVID-19 has had an immense impact on the entire world for the past two years and a half. Thankfully, the development of the vaccine has helped mitigate some of the damage and that can be seen in our findings."),
  p("As demonstrated by our map, countries that have been affected the most by the pandemic with a significant amount of cases also have a significant amount of vaccinated individuals."),
  p("The United States, India, Brazil, and Myanmar have had the highest number of COVID-19 cases, and we observed that the United States, China, India, and Brazil have the highest vaccination rates."),
  br(),
  h5("Additionally, our observations show that the relationship between new deaths and vaccines is highly correlated."),
  p("As more vaccines continue to be administered, the rate of new deaths due to COVID-19 decreases. "),
  h5("This further emphasises the effect the development of vaccines has had on the world since the first reported cases of the virus."),
  br(),
  h5("Finally, cases of new deaths appear to be reducing overtime although some peaks in new deaths can be seen here and there."),
  p("The ebbs and lows can most likely be attributed to variants of COVID that have arised through time."),
  h5("Though for the most part in most countries across the word, cases of new deaths can be seen diminishing")

)


ui <- navbarPage(
  "Covid Cases and Vaccinations",
  theme = shinytheme("flatly"),
  introduction,
  chart_1_page,
  chart_2_page,
  chart_3_page,
  conclusion
)
